# Generated by Django 5.2.17 on 2026-09-07 08:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConditionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60, unique=True)),
                ('tone', models.CharField(choices=[('neutral', 'Neutral'), ('caution', 'Caution')], default='neutral', max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('position', 'label'),
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('short_name', models.CharField(blank=True, max_length=40)),
                ('address', models.TextField(blank=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalParticipant',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('allergies', models.TextField(blank=True)),
                ('mobility', models.TextField(blank=True)),
                ('communication', models.TextField(blank=True)),
                ('emergency_contacts', models.TextField(blank=True)),
                ('shift_alert', models.CharField(blank=True, help_text="One line shown on the dashboard row, e.g. 'Do not leave unattended near stairs'.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.home')),
            ],
            options={
                'verbose_name': 'historical participant',
                'verbose_name_plural': 'historical participants',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('preferred_name', models.CharField(blank=True, max_length=80)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('allergies', models.TextField(blank=True)),
                ('mobility', models.TextField(blank=True)),
                ('communication', models.TextField(blank=True)),
                ('emergency_contacts', models.TextField(blank=True)),
                ('shift_alert', models.CharField(blank=True, help_text="One line shown on the dashboard row, e.g. 'Do not leave unattended near stairs'.", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='people.home')),
                ('tags', models.ManyToManyField(blank=True, related_name='participants', to='people.conditiontag')),
            ],
            options={
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('worker', 'Support worker'), ('manager', 'Manager')], default='worker', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('homes', models.ManyToManyField(blank=True, related_name='staff', to='people.home')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
