# Generated by Django 5.2.17 on 2026-09-07 08:01

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(help_text='The date the shift started.')),
                ('shift', models.CharField(choices=[('morning', 'Morning shift'), ('afternoon', 'Afternoon shift'), ('night', 'Night shift')], max_length=12)),
                ('schema_key', models.CharField(default='daily_care', max_length=60)),
                ('schema_version', models.CharField(default='v02', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('not_required', 'Not required'), ('void', 'Void')], default='draft', max_length=14)),
                ('not_required_reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('shower', models.BooleanField(blank=True, null=True)),
                ('bed_bath', models.BooleanField(blank=True, null=True)),
                ('physio_completed', models.BooleanField(blank=True, null=True)),
                ('bowel_recorded', models.BooleanField(default=False)),
                ('urine_recorded', models.BooleanField(default=False)),
                ('fluids_recorded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records_created', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='people.home')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='records', to='people.participant')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='records_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-service_date', '-submitted_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCareRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('service_date', models.DateField(help_text='The date the shift started.')),
                ('shift', models.CharField(choices=[('morning', 'Morning shift'), ('afternoon', 'Afternoon shift'), ('night', 'Night shift')], max_length=12)),
                ('schema_key', models.CharField(default='daily_care', max_length=60)),
                ('schema_version', models.CharField(default='v02', max_length=20)),
                ('answers', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('not_required', 'Not required'), ('void', 'Void')], default='draft', max_length=14)),
                ('not_required_reason', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=30)),
                ('shower', models.BooleanField(blank=True, null=True)),
                ('bed_bath', models.BooleanField(blank=True, null=True)),
                ('physio_completed', models.BooleanField(blank=True, null=True)),
                ('bowel_recorded', models.BooleanField(default=False)),
                ('urine_recorded', models.BooleanField(default=False)),
                ('fluids_recorded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('home', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.home')),
                ('participant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='people.participant')),
                ('submitted_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical care record',
                'verbose_name_plural': 'historical care records',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OvernightAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='records.carerecord')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='RecordAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='records.carerecord')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('export', 'Exported'), ('submit', 'Submitted'), ('amend', 'Amended'), ('void', 'Voided')], max_length=12)),
                ('target', models.CharField(max_length=200)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['actor', '-created_at'], name='records_aud_actor_i_b96230_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='carerecord',
            index=models.Index(fields=['home', 'service_date'], name='records_car_home_id_ab5a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='carerecord',
            index=models.Index(fields=['participant', 'service_date'], name='records_car_partici_0b96a0_idx'),
        ),
        migrations.AddIndex(
            model_name='carerecord',
            index=models.Index(fields=['status', 'service_date'], name='records_car_status_42f1fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='carerecord',
            constraint=models.UniqueConstraint(fields=('participant', 'service_date', 'shift', 'schema_key'), name='one_record_per_participant_shift_form'),
        ),
    ]
