# Generated by Django 5.2.17 on 2026-09-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='records/%Y/%m/')),
                ('sha256', models.CharField(max_length=64)),
                ('page_count', models.PositiveSmallIntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='records.carerecord')),
            ],
        ),
    ]
