# Generated by Django 5.2.17 on 2026-09-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfgen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recorddocument',
            name='page_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
